### ISSUE TITLE
DMS_MissionTimeout

### ISSUE THREAD

**Issue by azhizhinov** [Defent/DMS_Exile#55]
Hello there.
I might be wrong, but "DMS_MissionTimeout" haven't used in your code at all, except in the config.sqf itself.
And I have problem with the timeouts in a whole. Missions, static and dynamic, both, are will never expire with the default config.sqf.
"DMS_MaxStaticMissions" is often ignored, and every DMS_fnc_selectMission interaction will generate new server thread.

http://www.exilemod.com/topic/61-dms-defents-mission-system/?page=270

Good luck.

**Comment by HIMjack666** [comment]
Same problem since ARMA 1.68 update

**Comment by eraser1** [comment]
`DMS_MissionTimeout` is used in the default missions and fn_AddMissionToMonitor*

Timeout issues should be fixed with latest update.

MaxStaticMissions will be ignored by missions designated to begin on server start.

selectMission shouldn't generate a new thread unless BIS changed something (out of my control) or you have a spawn in there.

**Comment by azhizhinov** [comment]
Hello there.

Sorry, man, but issues still exists.

Good luck.

**Comment by azhizhinov** [comment]
Hello.

Sorry, man, I've tried you last fixes without any luck.
Mission timeouts do not honors, still.
Your last fully working version from September 7, 2017 still in use, thanks for that.
Good luck.

**Comment by eraser1** [comment]
Max Static missions should be fixed now.

Keep in mind that missions will not time out if:
1) a player is nearby
2) the number of AI in the mission has changed recently.

So if you have either of those cases (and/or AI killing each other), the mission will not time out.

Also, I did recently observe missions successfully timing out, so I know that this isn't an issue with vanilla exile and DMS.

Perhaps you can enable some debugging logs and see what's going on?

**Comment by azhizhinov** [comment]
Hello.
I've tried the new code once again with no luck.
I've replaced only missions and config.sqf and missions are not expired.
Your old code with this [fixes](http://www.exilemod.com/topic/61-dms-defents-mission-system/?do=findComment&comment=176089) is working fine.

Good luck.
